#!/bin/bash

apt-get install libtcltk-ruby
apt-get install libtrollop-ruby
apt-get install vim-gnome




cp scripts/git-review /usr/local/bin/git-review
chown root /usr/local/bin/git-review


cp scripts/git-review-format /usr/local/bin/git-review-format
chown root /usr/local/bin/git-review-format


cp scripts/git-review-log /usr/local/bin/git-review-log
chown root /usr/local/bin/git-review-log

cp scripts/git-review-log-limit /usr/local/bin/git-review-log-limit
chown root /usr/local/bin/git-review-log-limit

cp scripts/git-review-log-show /usr/local/bin/git-review-log-show
chown root /usr/local/bin/git-review-log-show

cp scripts/git-review-log-reviewer /usr/local/bin/git-review-log-reviewer
chown root /usr/local/bin/git-review-log-reviewer

cp scripts/git-reviewmbox /usr/local/bin/git-reviewmbox
chown root /usr/local/bin/git-reviewmbox

cp scripts/git-display /usr/local/bin/git-display
chown root /usr/local/bin/git-display

cp scripts/git-displaygui /usr/local/bin/git-displaygui
chown root /usr/local/bin/git-displaygui

cp scripts/patch-commit-linker/parsePatches.pl /usr/local/bin/parsePatches.pl
chown root /usr/local/bin/parsePatches.pl

cp scripts/patch-commit-linker/searchMatch.pl /tmp/searchMatch.pl

cp scripts/msg_to_commit.pl /usr/local/bin/msg_to_commit.pl
chown root /usr/local/bin/msg_to_commit.pl

cp scripts/git-update-review /usr/local/bin/git-update-review
chown root /usr/local/bin/git-update-review

mkdir -p /usr/local/share/man/man1
gzip -c doc/git-review.1 > /usr/local/share/man/man1/git-review.1.gz
chown root:root /usr/local/share/man/man1/git-review.1.gz

echo -e "git-review installed successfully"
