#!/bin/bash


cp scripts/git-review /usr/local/bin/git-review
chown root:root /usr/local/bin/git-review


cp scripts/git-review-format /usr/local/bin/git-review-format
chown root:root /usr/local/bin/git-review-format


cp scripts/git-review-log /usr/local/bin/git-review-log
chown root:root /usr/local/bin/git-review-log


cp scripts/git-review-log-show /usr/local/bin/git-review-log-show
chown root:root /usr/local/bin/git-review-log-show

cp scripts/git-review-log-author /usr/local/bin/git-review-log-author
chown root:root /usr/local/bin/git-review-log-author

cp scripts/git-reviewmbox /usr/local/bin/git-reviewmbox
chown root:root /usr/local/bin/git-reviewmbox

cp scripts/git-display /usr/local/bin/git-display
chown root:root /usr/local/bin/git-display

cp scripts/git-displaygui /usr/local/bin/git-displaygui
chown root:root /usr/local/bin/git-displaygui

mkdir -p /usr/local/share/man/man1
gzip -c doc/git-review.1 > /usr/local/share/man/man1/git-review.1.gz
chown root:root /usr/local/share/man/man1/git-review.1.gz
