#!/usr/bin/env ruby

require 'tk'
require 'tkextlib/tile'

f = File.open('/tmp/newfile.tmp',"r") 
r= File.open('/tmp/oldfile.tmp',"r") 
root = TkRoot.new { title "git-review" }

text = TkText.new(root) do

    width = TkWinfo.screenwidth root 
    height = TkWinfo.screenheight root
    borderwidth 1
    foreground 'dark green'
    font TkFont.new('tahoma 10')
    pack("side" => "left",  "padx"=> "3", "pady"=> "3")
end
 

f.each_line do |line|
text.insert 'end',line

end

text1 = TkText.new(root) do

   width = TkWinfo.screenwidth root
   height = TkWinfo.screenheight root
   borderwidth 1
   foreground 'red'
   font TkFont.new('tahoma 10')
   pack("side" => "right",  "padx"=> "3", "pady"=> "3")

end


r.each_line do |line|
text1.insert 'end',line

end

scroll_bar1 = TkScrollbar.new(root, 'orient'=>'ver', 
             'command' => proc { |*args| text1.yview *args}) 
scroll_bar1.pack('side' => 'right', 'fill' => 'y') 
text1.yscrollcommand(proc { |first,last| 
                                  scroll_bar1.set(first,last) })

scroll_bar = TkScrollbar.new(root, 'orient'=>'ver', 
             'command' => proc { |*args| text.yview *args}) 
scroll_bar.pack('side' => 'left', 'fill' => 'y') 
text.yscrollcommand(proc { |first,last| 
                                  scroll_bar.set(first,last) })

text.pack("fill"=>"y")
text.pack("expand"=>true)
text1.pack("fill"=>"y")
text1.pack("expand"=>true)
Tk.mainloop
