#!/usr/bin/env ruby

f = File.open('/tmp/newfile.tmp',"r") 
r= File.open('/tmp/oldfile.tmp',"r") 
require 'tk'
require 'tkextlib/tile'
root = TkRoot.new { title "git-review" }
ary=Array.new

text = TkText.new(root) do

width = TkWinfo.screenwidth root
height = TkWinfo.screenheight root

  borderwidth 4
  foreground 'dark green'
  font TkFont.new('tahoma 12')
   pack("side" => "left",  "padx"=> "5", "pady"=> "5")
end


f.each_line do |line|
text.insert 'end',line

end

text = TkText.new(root) do

  width = TkWinfo.screenwidth root
height = TkWinfo.screenheight root
  borderwidth 4
  foreground 'red'
  
  font TkFont.new('tahoma 12')
   pack("side" => "right",  "padx"=> "5", "pady"=> "5")
end


r.each_line do |line|
text.insert 'end',line

end

Tk.mainloop
