#!/usr/bin/env ruby

f = File.open('C:\Users\Murtuza\murtuza3\newfile.tmp',"r") 
r= File.open('C:\Users\Murtuza\murtuza3\oldfile.tmp',"r") 
require 'tk'
require 'tkextlib/tile'
root = TkRoot.new { title "dGui" }
ary=Array.new

text = TkText.new(root) do
width 100
  height 200
  borderwidth 1
  foreground 'dark green'
  font TkFont.new('tahoma 12 bold')
   pack("side" => "left",  "padx"=> "5", "pady"=> "5")
end


f.each_line do |line|
text.insert 'end',line

end

text = TkText.new(root) do
  width 100
  height 200
  borderwidth 1
  foreground 'red'
  
  font TkFont.new('tahoma 12 bold')
   pack("side" => "right",  "padx"=> "5", "pady"=> "5")
end


r.each_line do |line|
text.insert 'end',line

end


Tk.mainloop