#!/usr/bin/env perl


use strict;
my $inside_diff = 0;
my $counter = 0;
my $pos = 1;
my $comment;
my $comment1;
my $oldline;
my $posnew;
my $posold;
my $review_hash = $ARGV[0];

my $show = `git show $review_hash`;  


open(my $info, '> /tmp/review1.tmp');
print $info "$show";
close $info;
my $file = '/tmp/review1.tmp';
open my $info1, $file or die "Could not open $file: $!";



my $filenew = '/tmp/newfile.tmp';
my $fileold = '/tmp/oldfile.tmp';

open(my $fh, '>', $filenew) or die "Could not open file '$filenew' $!";

open(my $fo, '>', $fileold) or die "Could not open file '$fileold' $!";
my $old;
my $new;

my $value = 1;
while(my $line = <$info1>) {
       
       
        #$line =~ s/\>//g;
         
         if ( $value == 1 and $line =~ /^From/)
           {  $value = 0; 
              print "this is linux review";
              

          while(my $line = <$info1>) {
               if ($line =~ /^diff/xms)
  
                   { 
                     $inside_diff = 1;
                    print $fh "*****************************************************************\n";
                     print $fo "*****************************************************************\n";
                      print $fh "*****************************************************************\n";
                     print $fo "*****************************************************************\n";
                     print $fh "$line"; 
                    
                     print $fo "$line"; 
                    }
               elsif ($line =~ /^index/xms) 
                   {
                     print $fh "$line"; 
                     print $fo "$line"; 
                    }
  
              elsif ($line =~ /^\-\-\-/xms) 
                   {
                     print $fh "$line"; 
                     print $fo "$line"; 
                    }
  

               elsif ($line =~ /^\+\+\+/xms) 
                   { 
                     print $fh "$line"; 
                     print $fo "$line"; 
                    }
  

                elsif ($line =~ /^\@\@/xms) 
                   {
                     print $fh "$line"; 
                     print $fo "$line"; 
                     print $fh "--\n";
                     print $fo "--\n";
                    }
                
               elsif($line =~ /^\+/)  {
                
		
                
                print $fo "\n";
                print $fo "__________________________________________________________________________________________________\n";
                print $fh "$line"; 
                print $fh "__________________________________________________________________________________________________\n";
             
                
	}

         elsif($line =~ /^\-/)  {
                
                
		
               print $fh "\n"; 
               print $fh "__________________________________________________________________________________________________\n";
              print $fo "$line"; 
              print $fo "__________________________________________________________________________________________________\n";
               
          
	}
        elsif($line =~ /^\s/) { 
          print $fo "$line"; 
          print $fo "__________________________________________________________________________________________________\n";
           print $fh "$line";
           print $fh "__________________________________________________________________________________________________\n"; 
          
          }
         else {
                   print $fh "$line";
                   print $fh "__________________________________________________________________________________________________\n";
                  print $fo "$line";
                 print $fo "__________________________________________________________________________________________________\n";
            }
       }
      }  	

#--------------------------------------------------------------------------------------------------------
           if($line =~ /^>diff/xms) {
	 	
                     $inside_diff = 1;
                     print $fh "*****************************************************************\n";
                     print $fo "*****************************************************************\n";
                      print $fh "*****************************************************************\n";
                     print $fo "*****************************************************************\n";
                     print $fh "$line"; 
                     print $fo "$line"; 
                    }
               elsif ($line =~ /^>index/xms) 
                   {
                     print $fh "$line"; 
                     print $fo "$line"; 
                    }
  
              elsif ($line =~ /^>\-\-\-/xms) 
                   {
                     print $fh "$line"; 
                     print $fo "$line"; 
                    }
  

               elsif ($line =~ /^>\+\+\+/xms) 
                   { 
                     print $fh "$line"; 
                     print $fo "$line"; 
                    }
  

                elsif ($line =~ /^>\@\@/xms) 
                   {
                     print $fh "$line"; 
                     print $fo "$line"; 
                     print $fh "--\n";
                     print $fo "--\n";
                    }
                
               elsif($line =~ /^>\+/)  {
                
		
                
                print $fo "\n";
print $fo "__________________________________________________________________________________________________\n";
                print $fh "$line"; 
print $fh "__________________________________________________________________________________________________\n";
              
                
	}

         elsif($line =~ /^>\-/)  {
                
                
		
             print $fh "\n"; 
print $fh "__________________________________________________________________________________________________\n";
            print $fo "$line"; 
print $fo "__________________________________________________________________________________________________\n";
               
          
	}
        elsif($line =~ /^>\s/) { 
          print $fo "$line"; 
print $fo "__________________________________________________________________________________________________\n";
           print $fh "$line"; 
print $fh "__________________________________________________________________________________________________\n";
          
          }
      
        	
      #include comments

       
          
         elsif($oldline=~ /^>\-/xms){ 
                print $fo "\n";
              print $fo "$line";
               print $fo "\n";
              
            }
         elsif($oldline=~ /^>\+/xms)  {
                 
                 print $fh "\n";
                 print $fh "$line";
                 print $fh "\n";
            }
         elsif($oldline=~ /^>\s/xms)  {
                 print $fo "\n";
                 print $fh "\n";
                 print $fh "$line";
                  print $fo "$line";
                  print $fo "\n";
                 print $fh "\n";
       }
         else {
                   print $fh "$line";
                  print $fo "$line";
            }
                


      
 
 $oldline=$line;

}


system("git displaygui");
close $fh;
close $fo;
close $info1;
close(MYFILE);


