#!/usr/bin/perl

my $commithash = $ARGV[0];
my $flag = 0; 


if(length($commithash) != 0)
 {
   $flag =1;
 } 


OUTER:
foreach my $rev (`git rev-list review --pretty=oneline`) {
   
  ($sha=$rev) =~ s/\s.*$//;
   
  foreach my $blob (`git log --numstat -1 $sha`) {
 
my @values = (split('\t', $blob))[2];

  foreach my $val1 (@values) {


          my @values1 = (split('\/', $val1))[0];
           $val1 = (split('\/', $blob))[1];
         
          


foreach my $val (@values1) {
      

    if($flag == 1 && $val!=$commithash) {
            
            next OUTER;
  }
        
      print "\nReview ";
         
          print $val1;
      print "commit Reviewed ";
      print "$val\n";
 }


}
  
  }
   
   my $log = `git log -1 $sha`;

   
   my $log_amend = (split('Amended Review', $log))[1];
   my $log_response = (split('Response to', $log))[1];
   my $removemessage = (split('\n\n', $log))[0];
   
  
   print "$removemessage\n";
   
   if($log_amend)
    {
      print "Amended Review"; 
       print "$log_amend";
    }
   

    
   if($log_response)
    {
      print "Response to"; 
       print "$log_response";
    }
    
   
}
