#!/usr/bin/perl

my $commithash = $ARGV[0];
my $flag = 0; 
my $log = '';
my $check = 0;
if(length($commithash) != 0)
 {
   $flag =1;
 } 




my $rev = `git log --no-merges --numstat review`;
open my $fh, '<', \$rev or die $!;
while (<$fh>) {
   
       if (/^(?!commit)/) {
          $current = $current.$_;
       }
 
       else {
  
          $log =  "$current\n";
          my @authordetails = (split('\n', $log))[0..2];
          my @details = (split('\n', $log))[2..3];
          my @values = (split('\t', $log))[2];
          foreach my $val1 (@values) {
                my @values1 = (split('\/', $val1))[0];
                $val1 = (split('\/', $log))[1];
                $val1 =~ s/^\s+//;
	        $val1 =~ s/\s+$//; 
		foreach my $val (@values1) {
                   if($flag == 1 && $val ne $commithash) {
            
                      #do nothing
                   }
                  
                   else {
                      
                      print "\nReview ";
       		      print "$val1\n";
	              print "commit Reviewed ";
                      print "$val\n";
                      foreach(@authordetails){
 			 print "$_\n";
  		      }
                      foreach(@details){
  			 print "$_\n";
 		      }
                   }
                 }


             }
     


        $current = '';
       }
}
close $fh or die $!;

