#!/usr/bin/env ruby
#!/bin/sh


require 'rubygems'
require "trollop"
require "open3"
include Open3

review_log = `git review-log`

first_line = review_log.split(/\n/)
print first_line[1]
review_hash = first_line.split[1]         #Getting the print "hello"
print review_hash
                  
cmd = `git show #{review_hash}`
tree_hash= cmd.lines.first
tree_hash= tree_hash.split[1]             #Getting the tree the review belongs to

   
