#!/usr/bin/perl

my $author = $ARGV[0];
my $flag = 0; 
my $log = '';



my $rev = `git log --no-merges --numstat review`;
open my $fh, '<', \$rev or die $!;
while (<$fh>) {
   
       if (/^(?!commit)/) {
          $current = $current.$_;
       }

 else {
  
          $log =  "$current\n";
          
          
          
          my @authordetails = (split('\n', $log))[0..2];
          my @details = (split('\n', $log))[2..3];
          $removecheck = (split('Author: ', $log))[1];
          $removecheck = (split('\n', $removecheck))[0];
          $name = (split('\s', $removecheck))[0];
          $name = uc($name);
          $lastname = (split('\s', $removecheck))[1];
          $lastname = uc($lastname);
          $fullname = $name.$lastname;
       
          if ($name eq $author || $lastname eq $author || $fullname eq $author) {
    
                $flag=1;
          } 


          else {
               $flag=0;
    
          }       
          my @values = (split('\t', $log))[2];
          foreach my $val1 (@values) {
                my @values1 = (split('\/', $val1))[0];
                $val1 = (split('\/', $log))[1];
                $val1 =~ s/^\s+//;
	        $val1 =~ s/\s+$//; 
		foreach my $val (@values1) {
                   if($flag != 1) {
            
                      #do nothing
                   }
                  
                   else {
                      
                      print "\nReview ";
       		      print "$val1\n";
	              print "commit Reviewed ";
                      print "$val\n";
                      foreach(@authordetails){
 			 print "$_\n";
  		      }
                      foreach(@details){
  			 print "$_\n";
 		      }
                   }
                 }


             }
     


        $current = '';
       }
}
close $fh or die $!;


