#!/usr/bin/perl

my $commithash = $ARGV[0];
my $flag = 0; 
my $log = '';
my $check = 0;
if(length($commithash) != 0)
 {
   $flag =1;
 } 




my $rev = `git log --no-merges --numstat review --pretty=fuller`;
open my $fh, '<', \$rev or die $!;
while (<$fh>) {
   
       if (/^(?!commit)/) {
          $current = $current.$_;
       }
 
       else {
  
          $log =  "$current\n";
         
          my @authordetails = (split('\n', $log))[0..4];
          
          my @details = (split('\n', $log))[4..5];
          
          my @values = (split('\n', $log))[7];
          
          my $message = (split('\n', $log))[5];

         
         
         
         
          foreach my $val1 (@values) {
          
                
                my $val = (split('\/', $val1))[0];
                $val = (split('\t', $val))[2];
                $val1 = (split('\/', $val1))[1];
                
                $val1 =~ s/^\s+//;
	        $val1 =~ s/\s+$//;
                
		
                   if($flag == 1 && $val ne $commithash) {
            
                        #do nothing
                   }
                    
                   

                   else {
                       
                       #if($message =~ /has been deleted/)
               		#{
                    		#do nothing
               		#}
                      #else {    
                      print "\nReview: ";
       		      print "$val1\n";
	              print "Commit Reviewed: ";
                      print "$val\n";
                      foreach(@authordetails){
 			 if($_ =~ /^Commit:\s\s(.*)/)
                            {
                                 my $reviewer = $1;
                                 print "Reviewer:$reviewer\n";
                            }
                         elsif($_ =~ /^CommitDate:\s(.*)/)
                            {
                                 my $reviewdate = $1;
                                 print "ReviewDate: $reviewdate\n";
                            }
                        else {
 			 print "$_\n";

  		      }
  		      }
                      foreach(@details){
  			 print "$_\n";
 		      }
                   }
                 }


             #}
     


        $current = '';
       }
}
close $fh or die $!;

